version: "3.7"
services:
  web:
    build: .
    image: shift_manager/ruby:latest
    container_name: shift_manager_web
    command: "rails s -b 0.0.0.0"
    volumes:
      - ./:/app
    env_file:
      - ./.env
    depends_on:
      - database
    ports:
      - "3000:3000"
      - "587:587"
    stdin_open: true
    tty: true
  webpacker:
    image: shift_manager/ruby:latest
    container_name: shift_manager_webpacker
    command: ./bin/webpack-dev-server
    depends_on:
      - web
    ports:
      - 3035:3035
    environment:
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
  database:
    image: postgres:latest
    restart: always
    container_name: shift_manager_db
    volumes:
      - ../.postgres/data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"
